###submit
nano snaq_julia.sub
universe = vanilla
log =juliaread.log

executable = snaq_julia.sh

initialdir = snaq_julia$(ProcId)

arguments = raxmltrees.tre tableCF.csv julread.out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = raxmltrees.tre, tableCF.csv, julia-1.8.5-linux-x86_64.tar.gz, julia_snaq.jl, pro.tar.gz


log =julread.log
error = julread.err
output = julread.out

request_cpus = 8
request_memory = 2GB
request_disk = 2GB

queue 2
