universe = vanilla
log =juliaread.log

executable = toy4.sh

initialdir = chtc$(ProcId)

arguments = files.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = files.tar.gz, julia-1.8.5-linux-x86_64.tar.gz, network_estimation.jl, pro.tar.gz


log =julread.log
error = julread.err
output = julread.out

request_cpus = 8
request_memory = 10GB
request_disk = 10GB

queue 5
